# version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/timetracker
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=timetracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    name: timetracker-network
